apiVersion: v1
kind: Service
metadata:
  name: celery-redis
  labels:
    app: redis
    component: celery
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis
    component: celery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      component: celery
  template:
    metadata:
      labels:
        app: redis
        component: celery
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command: 
        - redis-server
        - --appendonly
        - "yes"
        - --appendfsync
        - everysec
        - --maxmemory
        - 256mb
        - --maxmemory-policy
        - allkeys-lru
        - --save
        - "900 1"
        - --save
        - "300 10"
        - --save
        - "60 10000"
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: celery-redis-data
          mountPath: /data
      volumes:
      - name: celery-redis-data
        persistentVolumeClaim:
          claimName: celery-redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi