# Development overrides for docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

services:
  # Nginx with local config volume mounts for development
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - acme-challenge:/var/www/html/.well-known/acme-challenge
      - ssl-certs:/etc/nginx/ssl
    environment:
      - PRODUCTION_MODE=false

  # API Service with hot reload for development
  api-service:
    volumes:
      - ./src:/app/src:ro
    environment:
      - RELOAD=true

  # Celery Worker with hot reload
  celery-worker:
    volumes:
      - ./src:/app/src:ro
    environment:
      - RELOAD=true

  # Storage Service with hot reload
  storage-service:
    volumes:
      - ./src:/app/src:ro
    environment:
      - RELOAD=true

  # Storage Worker with hot reload
  storage-worker:
    volumes:
      - ./src:/app/src:ro
    environment:
      - RELOAD=true

  # Executors with additional dev logging
  executor-1:
    environment:
      - LOG_LEVEL=DEBUG
  
  executor-2:
    environment:
      - LOG_LEVEL=DEBUG

  # Frontend with hot reload and source mounting
  crucible-frontend:
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules  # Preserve container's node_modules
      - /app/.next        # Preserve Next.js build cache
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Enable polling for file changes (needed in Docker)

# Volumes are inherited from base docker-compose.yml