# Build-time services only
# Usage: docker compose -f docker-compose.yml -f docker-compose.build.yml build

services:
  # Base image for all Python services
  base:
    image: ${BASE_IMAGE:-crucible-base}
    build:
      context: .
      dockerfile: shared/docker/base.Dockerfile

  # ML executor image with heavy dependencies
  executor-ml-image:
    image: ${EXECUTOR_ML_IMAGE:-executor-ml:latest}
    build:
      context: .
      dockerfile: docker/executor-ml/Dockerfile