[tool.ruff]
line-length = 100

[tool.ruff.format]
# Use consistent formatting
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pytest.ini_options]
# Add project root to Python path for imports
pythonpath = ["."]
# Test discovery patterns
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
# Fix pytest-asyncio warning
asyncio_default_fixture_loop_scope = "function"
# Custom markers
markers = [
    # Test Categories
    "unit: marks tests as unit tests",
    "integration: marks tests as integration tests",
    "e2e: marks tests as end-to-end tests",
    "performance: marks tests as performance tests",
    "security: marks tests as security tests",
    "benchmark: marks tests as benchmarks (usually long-running)",
    "load: marks tests as load tests for stress testing",
    
    # Service Dependencies
    "api: marks tests as requiring API service",
    "redis: marks tests as requiring Redis",
    "celery: marks tests as requiring Celery workers",
    "docker: marks tests as requiring Docker daemon",
    "kubernetes: marks tests as requiring Kubernetes cluster",
    "database: marks tests as requiring PostgreSQL database",
    "storage: marks tests as requiring storage service",
    "executor: marks tests as requiring executor service",
    
    # Test Characteristics
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "destructive: marks tests that stop/restart services (deselect with '-m \"not destructive\"')",
    "chaos: marks tests as chaos tests that intentionally cause failures",
    "flaky: marks tests that may fail intermittently",
    "critical: marks tests that must pass for basic functionality",
    
    # Platform Features
    "priority_queue: marks tests for priority queue functionality",
    "dual_write: marks tests for dual write functionality",
    "resilience: marks tests for resilience and recovery",
    "concurrency: marks tests for concurrent execution",
    "timeout: marks tests for timeout functionality",
    "network_isolation: marks tests that require network policy enforcement",
]