[tool.ruff]
line-length = 100

[tool.ruff.format]
# Use consistent formatting
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pytest.ini_options]
# Add project root to Python path for imports
pythonpath = ["."]
# Test discovery patterns
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
# Custom markers
markers = [
    "destructive: marks tests that stop/restart services (deselect with '-m \"not destructive\"')",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]