# Install NGINX Ingress Controller
# Run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml
# Or use this customized version:

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
# ConfigMap for custom nginx settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  # Global rate limiting
  limit-req-status-code: "429"
  limit-req-burst-multiplier: "5"
  
  # Security headers
  add-headers: "ingress-nginx/custom-headers"
  
  # Hide nginx version
  server-tokens: "false"
  
  # Enable gzip
  use-gzip: "true"
  gzip-level: "6"
  gzip-types: "text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml"
  
  # Proxy timeouts (matching your config)
  proxy-connect-timeout: "60"
  proxy-send-timeout: "60"
  proxy-read-timeout: "60"
  
  # Client body size
  proxy-body-size: "50m"
---
# Custom headers ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx
data:
  X-Frame-Options: "DENY"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Strict-Transport-Security: "max-age=31536000; includeSubDomains"
  Referrer-Policy: "strict-origin-when-cross-origin"
  Content-Security-Policy: "default-src 'self' http: https: data: blob: 'unsafe-inline'"