openapi: 3.1.0
info:
  title: Crucible Executor Service
  description: Creates isolated containers for secure code execution using Docker
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health
      description: Health check endpoint
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /capacity:
    get:
      summary: Capacity
      description: Check if executor can accept new tasks - Kubernetes readiness probe
        pattern
      operationId: capacity_capacity_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /execute:
    post:
      summary: Execute
      description: 'Start code execution in an isolated container.

        Returns immediately with running status.'
      operationId: execute_execute_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /logs/{eval_id}:
    get:
      summary: Get Logs
      description: Get current logs from a running or completed container
      operationId: get_logs_logs__eval_id__get
      parameters:
      - name: eval_id
        in: path
        required: true
        schema:
          type: string
          title: Eval Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogsResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /kill/{eval_id}:
    post:
      summary: Kill Execution
      description: Kill a running container
      operationId: kill_execution_kill__eval_id__post
      parameters:
      - name: eval_id
        in: path
        required: true
        schema:
          type: string
          title: Eval Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KillResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /status:
    get:
      summary: Status
      description: Get executor service status
      operationId: status_status_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /running:
    get:
      summary: List Running
      description: List all currently running executions
      operationId: list_running_running_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    ExecuteRequest:
      properties:
        eval_id:
          type: string
          title: Eval Id
        code:
          type: string
          title: Code
        timeout:
          type: integer
          title: Timeout
          default: 30
      type: object
      required:
      - eval_id
      - code
      title: ExecuteRequest
      description: Request to execute code
    ExecuteResponse:
      properties:
        eval_id:
          type: string
          title: Eval Id
        status:
          type: string
          title: Status
        output:
          type: string
          title: Output
          default: ''
        error:
          type: string
          title: Error
          default: ''
        exit_code:
          type: integer
          title: Exit Code
          default: -1
        executor_id:
          type: string
          title: Executor Id
          default: executor
        container_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Container Id
      type: object
      required:
      - eval_id
      - status
      title: ExecuteResponse
      description: Response from execution
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    KillResponse:
      properties:
        eval_id:
          type: string
          title: Eval Id
        success:
          type: boolean
          title: Success
        message:
          type: string
          title: Message
      type: object
      required:
      - eval_id
      - success
      - message
      title: KillResponse
      description: Response for kill operation
    LogsResponse:
      properties:
        eval_id:
          type: string
          title: Eval Id
        output:
          type: string
          title: Output
        error:
          type: string
          title: Error
          default: ''
        is_running:
          type: boolean
          title: Is Running
        exit_code:
          anyOf:
          - type: integer
          - type: 'null'
          title: Exit Code
      type: object
      required:
      - eval_id
      - output
      - is_running
      title: LogsResponse
      description: Response for container logs
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
