apiVersion: v1
kind: Pod
metadata:
  name: frontend-with-logger
spec:
  containers:
  # Main application
  - name: frontend
    image: crucible-platform/frontend:local
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/app
  
  # Sidecar that reads logs
  - name: log-reader
    image: busybox
    command: ['sh', '-c', 'while true; do echo "=== Log Reader Active ==="; ls -la /logs/; sleep 30; done']
    volumeMounts:
    - name: shared-logs
      mountPath: /logs
  
  volumes:
  - name: shared-logs
    emptyDir: {}