apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: crucible
    component: frontend
spec:
  type: LoadBalancer  # In kind, this will give us localhost access
  selector:
    app: crucible
    component: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP