apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  template:
    spec:
      containers:
      - name: celery-worker
        readinessProbe:
          exec:
            command:
            - celery
            - -A
            - celery_worker.celery_app
            - inspect
            - ping
          initialDelaySeconds: 30  # Give more time for startup
          periodSeconds: 20        # Check less frequently
          timeoutSeconds: 15       # Allow more time for the probe
          failureThreshold: 5      # Allow more failures before marking unready