apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-dispatcher
  namespace: crucible
rules:
# Add node access for querying images in local dev
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]