# Add environment variables for local development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  template:
    spec:
      containers:
      - name: dispatcher
        env:
        - name: REGISTRY_PREFIX  
          value: "503132503803.dkr.ecr.us-west-2.amazonaws.com"
        - name: ENVIRONMENT
          value: "local"