apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  template:
    spec:
      containers:
      - name: dispatcher
        env:
        - name: HOST_OS
          value: "macos"  # Override for macOS development
        - name: GVISOR_AVAILABLE
          value: "false"  # gVisor doesn't work on macOS with Kind