# Reduce replicas for local development
# Storage service to 1 replica due to RWO limitation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
spec:
  replicas: 1
---
# Reduce other services to 1 replica to save resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-worker
spec:
  replicas: 1
# Executors removed - Celery now creates Kubernetes Jobs directly