apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 1  # Default to 1, scale up in production
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    # This is your Pod template - looks familiar?
    metadata:
      labels:
        app: frontend-deployment
    spec:
      priorityClassName: high-priority
      containers:
      - name: frontend
        image: crucible-platform/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://api-service:8080"
        - name: HOSTNAME
          value: "0.0.0.0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"