apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # API Service Configuration
  API_LOG_LEVEL: "INFO"
  API_PORT: "8080"
  
  # Storage Configuration
  STORAGE_BACKEND: "database"
  FALLBACK_BACKEND: "file"
  ENABLE_CACHING: "true"
  FILE_STORAGE_PATH: "/app/data"
  
  # Celery Configuration
  CELERY_ENABLED: "true"
  CELERY_PERCENTAGE: "1.0"
  CELERY_CONCURRENCY: "2"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "100"
  CELERY_WORKER_PREFETCH_MULTIPLIER: "4"
  
  # Executor Configuration
  EXECUTOR_COUNT: "2"
  MAX_CONCURRENT_EXECUTIONS: "1"
  
  # General Configuration
  PYTHONUNBUFFERED: "1"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
        use epoll;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;

        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml application/atom+xml image/svg+xml;

        # Upstream definitions
        upstream api_backend {
            server api-service:8080;
        }

        upstream frontend_backend {
            server crucible-frontend:3000;
        }

        upstream flower_backend {
            server flower-service:5555;
        }

        # Main server block
        server {
            listen 80;
            server_name _;

            location /api/ {
                proxy_pass http://api_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /flower/ {
                proxy_pass http://flower_backend/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location / {
                proxy_pass http://frontend_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }