apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-images
  annotations:
    # Force Skaffold to build/load these images
    skaffold.dev/load-images: "crucible-platform/executor-base"
data:
  # Default executor images
  images.yaml: |
    images:
      - name: "executor-base"
        image: "executor-base"
        description: "Basic Python 3.11 environment"
      - name: "executor-ml"
        image: "executor-ml"
        description: "Python with ML libraries (PyTorch, NumPy, etc.)"
        default: true