# Service for Flower (Celery monitoring) if you're using it
apiVersion: v1
kind: Service
metadata:
  name: flower-service
  namespace: crucible
spec:
  selector:
    app: flower
  ports:
  - name: http
    port: 5555
    targetPort: 5555
  type: ClusterIP
---
# Basic Flower deployment (adjust as needed)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: crucible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: PLACEHOLDER_ECR_REGISTRY/crucible-platform:flower-latest
        ports:
        - containerPort: 5555
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379/0"
        - name: FLOWER_BASIC_AUTH
          valueFrom:
            secretKeyRef:
              name: flower-auth
              key: basic-auth  # Format: username:password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"