# ClusterRole and ClusterRoleBinding for dispatcher to check gVisor RuntimeClass
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-dispatcher-cluster
  labels:
    app.kubernetes.io/name: dispatcher
    app.kubernetes.io/component: security
rules:
  # Allow reading runtime classes for gVisor checks
  - apiGroups: ["node.k8s.io"]
    resources: ["runtimeclasses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-dispatcher-cluster
  labels:
    app.kubernetes.io/name: dispatcher
    app.kubernetes.io/component: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-dispatcher-cluster
subjects:
  - kind: ServiceAccount
    name: job-dispatcher
    # namespace will be set by kustomize