# Evaluation request contract used across services
openapi: 3.1.0
info:
  title: Evaluation Request
  version: 1.0.0
components:
  schemas:
    EvaluationRequest:
      type: object
      description: Request to create a new evaluation
      required:
        - code
      properties:
        code:
          type: string
          description: Code to be evaluated
        language:
          type: string
          description: Programming language
          default: python
        engine:
          type: string
          description: Execution engine to use
          default: docker
          enum:
            - docker
            - gvisor
            - kubernetes
        timeout:
          type: integer
          description: Timeout in seconds
          default: 30
          minimum: 1
          maximum: 3600
        priority:
          type: boolean
          description: High priority flag for queue jumping
          default: false
      example:
        code: "print('Hello, World!')"
        language: python
        engine: docker
        timeout: 30