# Event contracts for inter-service communication
# These define the structure of events published to Redis
openapi: 3.1.0
info:
  title: Shared Event Contracts
  version: 1.0.0
components:
  schemas:
    # Note: These schemas match the actual implementation in executor-service/app.py
    # and storage-worker/app.py. Any changes here require updating those services.
    
    # Evaluation queued - Published by API when evaluation is submitted
    EvaluationQueuedEvent:
      type: object
      required:
        - eval_id
        - code
      properties:
        eval_id:
          type: string
          description: The evaluation identifier
        code:
          type: string
          description: Python code to execute
        language:
          type: string
          default: python
          description: Programming language (currently only python supported)
        metadata:
          type: object
          description: Additional metadata for the evaluation
          
    # Evaluation running - Published by queue-worker when executor starts
    EvaluationRunningEvent:
      type: object
      required:
        - eval_id
        - executor_id
        - container_id
      properties:
        eval_id:
          type: string
          description: The evaluation identifier
        executor_id:
          type: string
          description: ID of the executor service handling this evaluation
        container_id:
          type: string
          description: Docker container ID where code is running
        timeout:
          type: integer
          default: 30
          description: Execution timeout in seconds
              
    # Evaluation completed - Published by executor when container exits
    EvaluationCompletedEvent:
      type: object
      required:
        - eval_id
        - status
        - exit_code
        - executor_id
        - completed_at
      properties:
        eval_id:
          type: string
          description: The evaluation identifier
        status:
          type: string
          enum: [completed, failed, timeout]
          description: Final status based on exit code
        output:
          type: string
          description: Standard output from the evaluation
        error:
          type: string
          description: Standard error from the evaluation
        exit_code:
          type: integer
          description: Process exit code (0=success, 124=timeout, other=error)
        executor_id:
          type: string
          description: ID of the executor that ran this
        completed_at:
          type: string
          format: date-time
          description: ISO timestamp of completion
              
    # Evaluation failed - Published by queue-worker if executor rejects/fails
    EvaluationFailedEvent:
      type: object
      required:
        - eval_id
        - error
      properties:
        eval_id:
          type: string
          description: The evaluation identifier
        error:
          type: string
          description: Error message explaining the failure
        executor_id:
          type: string
          description: ID of executor if failure occurred during execution
          
    # Generic evaluation event - For audit trail and history
    EvaluationEvent:
      type: object
      description: Generic event in evaluation lifecycle
      required:
        - evaluation_id
        - timestamp
        - event_type
        - message
      properties:
        id:
          type: integer
          description: Event ID (if stored in database)
        evaluation_id:
          type: string
          description: The evaluation this event belongs to
        timestamp:
          type: string
          format: date-time
          description: When the event occurred
        event_type:
          type: string
          description: Type of event (e.g., status_change, output_update)
        message:
          type: string
          description: Human-readable event message
        metadata:
          type: object
          description: Additional event-specific data
          additionalProperties: true