apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1  # Default to 1, scale up in production
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      priorityClassName: critical-priority
      containers:
      - name: celery-worker
        image: crucible-platform/celery-worker
        imagePullPolicy: Always
        command: ["python", "celery_worker/run_worker.py"]
        ports:
        - containerPort: 8088
          name: health
        env:
        - name: CELERY_BROKER_URL
          value: "redis://celery-redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://celery-redis:6379/1"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8082"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        - name: CELERY_CONCURRENCY
          value: "2"
        - name: DISPATCHER_SERVICE_URL
          value: "http://dispatcher-service:8090"
        - name: CELERY_WORKER_MAX_TASKS_PER_CHILD
          value: "100"
        - name: CELERY_WORKER_PREFETCH_MULTIPLIER
          value: "4"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 200Mi
      securityContext:
        seccompProfile:
          type: RuntimeDefault