apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3  # More replicas in production
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "256Mi"  # More resources in production
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"