apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# Production-specific patches
patchesStrategicMerge:
  - deployment-patch.yaml

# Override images for production
images:
  - name: PLACEHOLDER_ECR_REGISTRY/crucible-platform
    newTag: frontend-PLACEHOLDER_TAG
    
# Production config
configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=production
      - API_URL=https://api.crucible.example.com
      
# Production resources
resources:
  - hpa.yaml  # Horizontal Pod Autoscaler for production