# Reduce resource requirements for local development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
spec:
  template:
    spec:
      containers:
      - name: storage-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-worker
spec:
  template:
    spec:
      containers:
      - name: storage-worker
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"