# Resource optimization patches for dev environment
# Reduces both CPU and memory limits to prevent overcommitment on 2 CPU / 8GB node
# Total savings: ~850m CPU, ~960Mi memory limits

# Dispatcher - reduce CPU limit from 500m to 200m, memory from 256Mi to 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: dispatcher
        resources:
          limits:
            cpu: 200m
            memory: 128Mi

# Postgres - reduce CPU from 500m to 300m, memory from 512Mi to 256Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          limits:
            cpu: 300m
            memory: 256Mi

# Celery Worker - reduce CPU from 500m to 300m, memory from 512Mi to 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  template:
    spec:
      containers:
      - name: celery-worker
        resources:
          limits:
            cpu: 300m
            memory: 256Mi

# Celery Redis - reduce from 500m to 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            cpu: 200m

# Storage Service - reduce CPU from 200m to 150m, memory from 384Mi to 192Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
spec:
  template:
    spec:
      containers:
      - name: storage-service
        resources:
          limits:
            cpu: 150m
            memory: 192Mi

# Storage Worker - reduce from 500m to 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-worker
spec:
  template:
    spec:
      containers:
      - name: storage-worker
        resources:
          limits:
            cpu: 200m

# API Service - reduce from 500m to 300m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  template:
    spec:
      containers:
      - name: api-service
        resources:
          limits:
            cpu: 300m

# Redis - reduce from 500m to 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            cpu: 200m

# Frontend - reduce CPU from 200m to 100m, memory from 256Mi to 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
      - name: frontend
        resources:
          limits:
            cpu: 100m
            memory: 128Mi