apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-worker
spec:
  replicas: 1  # Default to 1, scale up in production
  selector:
    matchLabels:
      app: storage-worker
  template:
    metadata:
      labels:
        app: storage-worker
    spec:
      priorityClassName: high-priority
      containers:
      - name: storage-worker
        image: crucible-platform/storage-worker
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database-url
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DISPATCHER_SERVICE_URL
          value: "http://dispatcher-service:8090"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8082"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: file-storage
          mountPath: /app/data
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: storage-pvc  # Shared with storage-service
      securityContext:
        seccompProfile:
          type: RuntimeDefault