apiVersion: v1
kind: Service
metadata:
  name: storage-service
  labels:
    app: storage-service
spec:
  ports:
  - port: 8082
    name: http
  selector:
    app: storage-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
spec:
  replicas: 1  # Default to 1, scale up in production
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      priorityClassName: critical-priority
      containers:
      - name: storage-service
        image: crucible-platform/storage-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database-url
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: STORAGE_BACKEND
          value: "database"
        - name: FALLBACK_BACKEND
          value: "file"
        - name: ENABLE_CACHING
          value: "true"
        - name: FILE_STORAGE_PATH
          value: "/app/data"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "384Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: file-storage
          mountPath: /app/data
        - name: tmp
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: storage-pvc
      - name: tmp
        emptyDir:
          sizeLimit: 100Mi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi