name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
      - '.github/workflows/deploy-service-template.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
        default: 'dev'

jobs:
  openapi-generation:
    name: Generate OpenAPI Specs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies for OpenAPI generation
      run: |
        pip install fastapi pyyaml pydantic
    
    - name: Generate OpenAPI specs
      run: |
        echo "📄 Generating OpenAPI specs for frontend build..."
        ./scripts/generate-all-openapi-specs.sh
    
    - name: Upload OpenAPI specs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openapi-specs
        path: |
          api/openapi.yaml
          storage_service/openapi.yaml

  deploy:
    needs: openapi-generation
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-service-template.yml
    with:
      service_name: frontend
      service_dir: frontend
      deployment_name: frontend-deployment
      ecr_repo: frontend
      container_name: frontend
      dockerfile_path: frontend/Dockerfile
      health_check_port: '3000'
      health_check_path: '/'
      environment: ${{ github.event.inputs.environment || 'dev' }}
    secrets: inherit