name: Deploy Docker Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-west-2' }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME || 'crucible-platform' }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME || 'crucible-platform' }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY || 'crucible-platform' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Required for OIDC
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'
    
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build the Docker image
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest
        
        # Push both tags
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest
        
        echo "✅ Pushed image: $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"
    
    - name: Update SSM parameter with new image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws ssm put-parameter \
          --name "/${{ env.PROJECT_NAME }}/docker-image" \
          --value "$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" \
          --type String \
          --overwrite
        
        echo "📝 Updated SSM parameter with new image"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to EC2 instances
      run: |
        # Find EC2 instances
        INSTANCE_IDS=$(aws ec2 describe-instances \
          --filters "Name=tag:Project,Values=${{ env.PROJECT_NAME }}" "Name=instance-state-name,Values=running" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)
        
        if [ -z "$INSTANCE_IDS" ]; then
          echo "❌ No EC2 instances found with Project=${{ env.PROJECT_NAME }} tag"
          exit 1
        fi
        
        echo "📡 Deploying to instances: $INSTANCE_IDS"
        
        # Get Docker image from SSM
        DOCKER_IMAGE=$(aws ssm get-parameter --name "/${{ env.PROJECT_NAME }}/docker-image" --query 'Parameter.Value' --output text)
        echo "🐳 Deploying Docker image: $DOCKER_IMAGE"
        
        # Send command to update and restart container
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids $INSTANCE_IDS \
          --document-name "AWS-RunShellScript" \
          --parameters '{"commands":[
            "#!/bin/bash",
            "set -e",
            "echo \"🚀 Starting Docker deployment\"",
            "",
            "# Login to ECR",
            "aws ecr get-login-password --region '$AWS_REGION' | docker login --username AWS --password-stdin $(echo '$DOCKER_IMAGE' | cut -d/ -f1)",
            "",
            "# Pull new image",
            "docker pull '$DOCKER_IMAGE'",
            "",
            "# Restart systemd service (which will pull and run the new image)",
            "echo \"🔄 Restarting crucible-docker service\"",
            "sudo systemctl restart crucible-docker.service",
            "",
            "# Wait for service to start",
            "sleep 10",
            "",
            "# Check service status",
            "if sudo systemctl is-active --quiet crucible-docker.service; then",
            "  echo \"✅ Service started successfully\"",
            "  sudo systemctl status crucible-docker.service --no-pager",
            "  echo \"\"",
            "  echo \"📋 Recent logs:\"",
            "  sudo journalctl -u crucible-docker.service -n 20 --no-pager",
            "else",
            "  echo \"❌ Service failed to start\"",
            "  sudo systemctl status crucible-docker.service --no-pager",
            "  sudo journalctl -u crucible-docker.service -n 50 --no-pager",
            "  exit 1",
            "fi"
          ]}' \
          --output text \
          --query 'Command.CommandId')
        
        echo "📋 SSM Command ID: $COMMAND_ID"
        echo "⏳ Waiting for deployment to complete..."
        
        # Wait for command to complete
        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id $(echo $INSTANCE_IDS | awk '{print $1}')
        
        # Get command output
        aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id $(echo $INSTANCE_IDS | awk '{print $1}') \
          --query '[Status,StandardOutputContent]' \
          --output text